name: "metis-mainnet"

services:
  l1dtl:
    image: metisdao/dtl:v0.1.2
    platform: linux/amd64
    stop_grace_period: 30s
    network_mode: host
    restart: unless-stopped
    volumes:
      - ./chaindata/l1dtl:/data
    env_file:
      - ./mainnet/l1dtl.env
      - .env
    healthcheck:
      test: ["CMD-SHELL", "curl http://127.0.0.1:7878"]
      interval: 5s
      timeout: 3s
      retries: 6
    logging:
      driver: "json-file"
      options:
        max-size: "2m"
        max-file: "10"

  l2geth:
    image: metisdao/l2geth:v0.1.2
    platform: linux/amd64
    restart: unless-stopped
    stop_grace_period: 2m
    network_mode: host
    env_file:
      - ./mainnet/l2geth.env
    depends_on:
      l1dtl:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "is-l2geth-stalled"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s
    volumes:
      - ./chaindata/l2geth:/root/.ethereum
    logging:
      driver: "json-file"
      options:
        max-size: "2m"
        max-file: "10"
